data_cfg:
  train_images_root: ./processed_datasets/UCF-QNRF/train_data/
  val_images_root: ./processed_datasets/UCF-QNRF/test_data/
  test_images_root: ./processed_datasets/UCF-QNRF/test_data/
  train_data_file: ./processed_datasets/UCF-QNRF/train_data/data_list/train.txt
  val_data_file: ./processed_datasets/UCF-QNRF/test_data/data_list/test.txt
  test_data_file: ./processed_datasets/UCF-QNRF/test_data/data_list/test.txt
